---
language: objective-c

before_install:
- brew update

install:
- sudo pip install ansible --quiet

before_script:
- cp tests/stack.yml ~/.stack.yml
- cp tests/galaxy.yml ~/.galaxy.yml

script:
- bash <(curl -s curl -L https://raw.githubusercontent.com/poetic/short-stack/master/install.sh) --skip-short-stack
- bash short-stack
- >
  short-stack
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)

notifications:
  slack:
    secure: AlOY0p4fygPrQnIdEDrDgEpRqHE93ZFDj9d+yGgCBrzWpC74D4zFJv6iApQ3IWi8x8Lv/JKSjV+5fBCr5+mMMQrlYQDcqV4mJIGND4lazkB1VTD3n/ofX6RCXb/fEYZBMSKfBBl9YtbSt3vKbJ7S+hL1mgE8PsJygw+x4FnNXWY=
